### ISSUE TITLE
For the Translation Group: Please leave your WeChat Name and Rainbow Wallet address in the Comment, we will send you IRIS rewards for gratitude.

### ISSUE THREAD

**Issue by shirleypyj** [irisnet/translation#28]

**Comment by lucas3s** [comment]
hello, Lucas's rainbow wallet is: iaa1artwvdmnmh2p9cjdnk2nct500qqrwwuau2aexu

**Comment by hxu2k** [comment]
红，iaa145f2jsq3ds8qqahjj0fplr5m7y8rwrll9ajhv8

**Comment by andre1116** [comment]
andre-tran，iaa1ravy97sjaq5zr5uhgfqw2tvdrjxld90lejsu2j

**Comment by meixi528** [comment]
iaa167z5pv2yy9rc0dztkgc4g3z0vak2n5y55n5j20

**Comment by meixi528** [comment]
美兮iaa167z5pv2yy9rc0dztkgc4g3z0vak2n5y55n5j20

**Comment by igorshumilo** [comment]
Good day! I have translated the white paper into Russian language. My githab id is -  igorshumilo. My rainbow wallet address - iaa105y0rg5p30q3frg97gjmr47ssw872lxzuduvt7

**Comment by Cosalleen** [comment]
alin’s GitHubID -- Cosalleen 

Rainbow钱包地址:
iaa1rs00pv6yvvaek7txrt8g9fjwj76yhuxk5cqyct

https://shimo.im/docs/7af915a54c7d4276/ 《team 介绍翻译对照版本》

**Comment by shirleypyj** [comment]
hello

**Comment by igorshumilo** [comment]
hello!

пт, 22 мар. 2019 г. в 09:57, shirleypyj <notifications@github.com>:

**Comment by luckyarthur** [comment]
wechat:Arthur, address: iaa1t4t7vae4klyqjq7tre2kdzkh4xagk795cgvxld
